### ISSUE TITLE
Website loading problems

### ISSUE THREAD

**Issue by tthibodeau** [mrpmorris/blazor-university#19]
I've been visiting the [blazor-university.com](https://blazor-university.com/) site quite often lately and have noticed a lot of loading issues.

As there is no way to report issues on the website, I thought I'd drop a note here.

Thanks for the amazing, informative site!

![sshot-18](https://user-images.githubusercontent.com/5246712/82084552-b004d400-96a8-11ea-8bf3-c1720d4f7f02.png)

**Comment by mrpmorris** [comment]
Hi

Thanks for notifying me. I had some problems with my host.

I have CloudFlare in front of my site for caching. I didn't have it set up quite right so a lot of requests were still making it through to my host. With the increased popularity of the site that has caused me to exceed my hosting quota.

I believe I have fixed the problem with caching now, so hopefully it will be okay from here onwards.
