### ISSUE TITLE
Component lifecycle/OnParametersSet

### ISSUE THREAD

**Issue by MarkStega** [mrpmorris/blazor-university#2]
The current text implies that OnParametersSet will not be called after StateHasChanged/OnAfterRender but my experience today indicates that in 'normal' rendering of a component there are two calls to OnParametersSet. I had some code that made a bad assumption and the second call brought that out.

**Comment by mrpmorris** [comment]
Which text in particular? I think the image makes it quite clear

**Comment by MarkStega** [comment]
Peter,
The text of OnParametersSet only speaks to repetitive calls if parameters are changed (the addition of the navigation commnet is useful). My experience is closer to the diagram that shows that it will be called by unspecified "Events".

My 'discovery' of the issue was in a custom navigator component that took a parameter in the form of 'ActiveId="ormanagerview"' to specify an initial selection stored in a class property of _ActiveId. This was working until a Blazor preview update in July when multiple calls to OnParametersSet started occuring. My symptom was that as I navigated using the component the subsequent OnParametersSet call would always reset the internal _ActiveId to the initial value. My solution was to protect the setting with a boolean that indicated 'FirstOnParameterSet'

Perhaps a couple of code snippets this would be more clear. These are from the component:
```
        private string _ActiveId { get; set; }
        private bool _IsFirstParameterSet = true;
```

```
        protected override void OnParametersSet()
        {
            base.OnParametersSet();

            if (_IsFirstParameterSet)
            {
                _ActiveId = ActiveId;
                _IsFirstParameterSet = false;
            }
        }
```

```
        // We just pass along our configured item name, so we don't need any parameters
        private bool OnClick(GCNavMenuSelection ev)
        {
            // Remember the active one's id and re-render
            _ActiveId = ev.SelectedItemId;
            StateHasChanged();

            // And pass it on to our consumer
            OnSelect.InvokeAsync(ev);
            return false;
        }
    }
```
and this is the component instantiation:
```
@namespace Optimiser.Shared

<GCNavMenu BrandLogo="_content/Optimiser.Components/Images/Optimium_Man_20.png"
           BrandText="Optimi$er.2020 (V3.1.0)"
           MenuItems="ItemList"
           ActiveId="ormanagerview"
           OnSelect="@(ev => OnSelect(ev))"
           @ref="m_MenuInstance"
           Color="white"
           BackgroundColor="black" />

<LogonStatus />
```
In any case, I think that a list of all of the events that cause a OnParametersChanged as well as a second list of the events that don't and create the StateHasChanged invocation would be useful.

**Comment by mrpmorris** [comment]
If you only want the first ever value of a parameter and to ignore all future updates you should override OnInitialized or OnInitializedAsync and grab the value there and store it away as a private member.

Although it seems odd that you'd want to do that. Are you changing the value from within the component? If so, shouldn't you be implementing two-way binding?

**Comment by MarkStega** [comment]
I didn't even realize that the parameter value was available during OnInit, it makes much more sense to grab it there. As you can see I am storing it in a private member and changing it in the  OnClick code. It is not directly viewed but drives which navmenu item is highlighted,

**Comment by mrpmorris** [comment]
Take a look at the page again.
https://blazor-university.com/components/component-lifecycles/

1. SetParametersAsync
2. OnInitialized/OnInitializedAsync
3. OnParametersSet/OnParametersSetAsync
4. OnAfterRender/OnAfterRenderAsync

**Comment by MarkStega** [comment]
Much better, the page is really improved.

**Comment by mrpmorris** [comment]
Thanks for your help!
