### ISSUE TITLE
Issues with appearance of sample code

### ISSUE THREAD

**Issue by danysdragons** [mrpmorris/blazor-university#23]
I find that the code samples provided on Blazor University have a very small font, making them difficult to read. I’m used to the Microsoft docs where the sample code is much bigger: https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1

I’m not too familiar with Wordpress, but does it provide a mechanism to let visitors to your site customize things like this?

---

One of the reasons I came to Blazor University in the first place is that I was frustrated with the appearance of the sample code provided by the Microsoft docs. In the sample code there, the vast majority of the `@code` blocks have no syntax highlighting, and thus look like dog poop. For example: https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1#child-to-parent-binding-with-chained-bind

Fortunately Blazor University is better in this area, but there still seems to be some inconsistency about applying syntax highlighting.

**Comment by mrpmorris** [comment]
Thanks for your feedback!

I've updated the style so that the code samples are font-sized at 1rem.

To demonstrate the highlighting, could you please provide me with a sample that is highlighted how you like, and one that is not?
