### ISSUE TITLE
Visual Studio cannot load the projects

### ISSUE THREAD

**Issue by shengjing2019** [mrpmorris/blazor-university#33]
I'm using VS2019 v16.6.4 and when I opened the `BlazorUniversity.sln`, all projects were failed to load. What am I doing wrong? Thanks.

**Comment by mrpmorris** [comment]
Have you installed the correct vs options?

https://blazor-university.com/overview/installing-blazor/

**Comment by shengjing2019** [comment]
I just had a chance to look more closely VS outputs an error message pointing to `global.json` asking for sdk "version": "3.1.301" while my machine has only 302 install. I bumped up the version and now the projects load. Thank you.
