### ISSUE TITLE
FluentValidation upgrade breaking change

### ISSUE THREAD

**Issue by Levinta** [mrpmorris/blazor-university#34]
Hello,
While trying to reproduce the use case and reuse the code, I've received error on the line 136 related to the ValidationContext
https://github.com/mrpmorris/blazor-university/blob/ec8d1f4461b792a93f23ae4d875e2c5b43dee3e4/src/Forms/CustomValidation/Components/FluentValidationValidator.cs#L136
Looks like they made some changes. According to the docs, there is no more non-generic ValidationContext
https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html?highlight=ValidationContext#removal-of-non-generic-validationcontext

**Comment by mrpmorris** [comment]
Can you upload a repro somewhere? I'm not having this problem.

**Comment by mrpmorris** [comment]
Fixed, thank you!
