### ISSUE TITLE
TabControl.razor dosn't work 

### ISSUE THREAD

**Issue by pylvr** [mrpmorris/blazor-university#35]
The templated componant 'TabControl' doesn't  work please fix it

**Comment by optiks** [comment]
I'm no Blazor expert... but how can you seriously think "does not work" is a legitimate bug report?

*What* doesn't work? What's the error" What's the repro? Come on!

**Comment by mrpmorris** [comment]
Yes, I require additional information, please.

1: What is the project name (or URL to the website page with the error)
2: What do you do
3: What do you expect to happen
4: What actually happens

Thanks

**Comment by otetsdiodor** [comment]
choose CreatingATabControl.csproj as a startup project
Trying to run it with VS2019 using IIS
nothing happens the iis doesn't run the site

**Comment by mrpmorris** [comment]
It might be a problem with your local IIS installation, because it's working fine here.

Try switching to Kestrel.
Also, try CTRL+F5
