### ISSUE TITLE
Very good tutorials just one comment to make

### ISSUE THREAD

**Issue by nkatz01** [mrpmorris/blazor-university#39]
Very good tutorials! I'm really grateful! 

Just one comment about this tutorial https://blazor-university.com/routing/navigating-our-app-via-code/#:~:text=Access%20to%20browser%20navigation%20from,particular%20interest%3B%20NavigateTo%20and%20LocationChanged%20.

You mention a non-existent file (something which you supposedly talked about in a previous tutorial) CounterBase. Did you mean to refer to ComponentBase?

**Comment by mrpmorris** [comment]
I'm not sure what that was about, probably something I later removed.

It has been fixed now, thanks for letting me know!
